In [5]:
import os
import time
from google.cloud import bigquery
import pandas as pd

In [2]:
# os.environ['GOOGLE_APPLICATION_CREDENTIALS'] = "airqual-342602-432af0e9cbd8.json"
# client = bigquery.Client()

In [3]:
# t1 = time.perf_counter_ns()

# sql = """
# SELECT
#   latitude,
#   longitude,
#   date_local,
#   event_type,
#   arithmetic_mean,
#   aqi,
#   state_name,
#   county_name
# FROM
#   `bigquery-public-data.epa_historical_air_quality.pm10_daily_summary`
# ORDER BY
#   date_local DESC
# """
# df = client.query(sql).to_dataframe()

# t2 = time.perf_counter_ns()


# df.to_csv("airquality_pm10_daily_summary.csv", index_label = False)
# print((t2-t1)*10**-9)

In [6]:
"""
data from https://www.kaggle.com/epa/epa-historical-air-quality?select=pm10_hourly_summary

column details:

latitude - The monitoring site’s angular distance north of the equator measured in decimal degrees.
longitude - The monitoring site’s angular distance east of the prime meridian measured in decimal degrees.
date_local - The calendar date for the summary. All daily summaries are for the local standard day (midnight to midnight) at the monitor.
event_type - Indicates whether data measured during exceptional events are included in the summary. A wildfire is an example of an exceptional event;
it is something that affects air quality, but the local agency has no control over. No Events means no events occurred. 
Events Included means events occurred and the data from them is included in the summary. Events Excluded means that events 
occurred but data form them is excluded from the summary. Concurred Events Excluded means that events occurred but only EPA 
concurred exclusions are removed from the summary. If an event occurred for the parameter in question, the data will have multiple records for each monitor.
arithmetic_mean - The average (arithmetic mean) value for the day.
aqi - The Air Quality Index for the day for the pollutant, if applicable.
state_name - The name of the state where the monitoring site is located.
county_name - The name of the county where the monitoring site is located.

datum used for lat and lon is WGS84
units of aqi are Micrograms/cubic meter (25 C)
"""

df = pd.read_csv("airquality_pm10_daily_summary.csv")

In [7]:
df.head()

,latitude,longitude,date_local,event_type,arithmetic_mean,aqi,state_name,county_name
0,38.588034,-82.834973,2019-12-31,Included,3.0,3,Ohio,Scioto
1,39.755969,-84.198674,2019-12-31,None,8.0,7,Ohio,Montgomery
2,61.181117,-149.834003,2019-12-31,None,7.0,6,Alaska,Anchorage
3,35.144300,-106.604680,2019-12-31,Included,18.0,17,New Mexico,Bernalillo
4,47.594395,-115.323746,2019-12-31,None,15.0,14,Montana,Sanders